### ISSUE TITLE
falha no envio

### ISSUE THREAD

**Issue by cusinato** [mineration/desafio-senac-2018#2]
Bom dia, não consigo submeter um arquivo .csv com as respostas:

- Erro ao receber o arquivo de resposta. Verifique se o formato está correto e se contém os ids de teste.

segue trecho inicial do meu arquivo:

1,0.17077
2,0.17077
3,0.17077
4,0.17077

Há algo de errado no formato dele?

**Comment by rnmourao** [comment]
Sim.

Essa não é a resposta, mas o exemplo. Os ids que vc deve enviar estão no arquivo avaliacoes_test.csv.
